### ISSUE TITLE
It doesn't work..

### ISSUE THREAD

**Issue by lancerossdev** [naomi-pham/portfolio#1]
Hey, your portfolio doesn't show anything idk why.. It doesn't show any content.

![image](https://user-images.githubusercontent.com/102563271/194522916-86a1cfa0-b0e2-4a59-8834-ddf9378ed070.png)

**Comment by naomi-pham** [comment]
Hi Lance,

Thanks so much for checking out my portfolio.

I struggled with deploying the app with Github and used Netlify instead.
Here is the link (https://naomi-pham.netlify.app/). It is still not done,
but I will update it in the next few days. I will also update the code on
GitHub in case you like to see the code.

How's it going with learning JavaScript with implementing Tailwind for your
website?

**Comment by naomi-pham** [comment]
Intimidating Tailwind utility classes at your service here! 😁

[image: image.png]
